on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        plan:
          - node-version: "24.0.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.plan.node-version }}
      - name: Install pnpm
        run: "npm i -g pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint & Type check
        run: pnpm lint && pnpm type-check
      - name: Build
        run: pnpm build
      - name: add nojekyll
        run: touch ./out/.nojekyll
      - name: Archive artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ github.sha }}-out
          path: out